### ISSUE TITLE
Error installing dependencies 

### ISSUE THREAD

**Issue by jobyid** [MihaelIsaev/braintree_swift#1]
Hi Mike, 

Thanks for putting this together, I am getting an error with the dependencies. I am very new to Vapor so it certainly could be me doing something wrong. 

`error: "error: the package braintree_swift[https://github.com/MihaelIsaev/braintree_swift] @ 0.1.0 contains incompatible dependencies:\n    xmlparsing[https://github.com/MihaelIsaev/XMLParsing.git] @ master\n",` 

Do you have any suggestions? 

Many Thanks 
Joby

**Comment by MihaelIsaev** [comment]
Hey, thank you for that issue! I've just fixed it in `v0.2.1`.
Could you please try to run `swift package update` to grab the fixed version.

**Comment by jobyid** [comment]
Perfect that works now. 
Thank you.
